### ISSUE TITLE
Bug: Error if the image is corrupted

### ISSUE THREAD

**Issue by ServOKio** [ztomm/express-responsive-images#2]
Version: 1.1.9
# Steps To Reproduce
Just mess up the image in any txt editor
# The expected behavior
You can add the onError option to the configuration, for example:
```js
app.use(
    responsiveImages({
        debug: true,
        onError: (req, res) => {
            res.status(500);
            res.send('Error');
        }
    })
);
```
Or you can send a "standard" image to the user if processing of the expected image failed.

```cmd
express-responsive-images: /assets/img/avatars/3961362381963509760/kHsSJS.png?w=128 --------------------------------------
express-responsive-images: (kHsSJS.png) requested directory is in watchlist: /assets/img/avatars/3961362381963509760
express-responsive-images: (kHsSJS.png) requested file: kHsSJS.png
express-responsive-images: (kHsSJS.png) filetype is supported: png
express-responsive-images: (kHsSJS.png) cookie "screen" is set: density=1.100000023841858, width=1752
express-responsive-images: (kHsSJS.png) new image width is probably 141
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
    at boundsError (internal/buffer.js:47:11)
    at Buffer.readUInt16LE (internal/buffer.js:204:5)
    at Object.validate (/home/admin/web/net/server/node_modules/image-size/dist/types/cur.js:7:20)
    at finder (/home/admin/web/net/server/node_modules/image-size/dist/detector.js:26:55)
    at Array.find (<anonymous>)
    at Object.detector (/home/admin/web/net/server/node_modules/image-size/dist/detector.js:27:17)
    at lookup (/home/admin/web/net/server/node_modules/image-size/dist/index.js:32:29)
    at imageSize (/home/admin/web/net/server/node_modules/image-size/dist/index.js:102:16)
    at /home/admin/web/net/server/node_modules/express-responsive-images/index.js:237:24
    at Layer.handle [as handle_request] (/home/admin/web/net/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/admin/web/net/server/node_modules/express/lib/router/index.js:317:13)
    at /home/admin/web/net/server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/admin/web/net/server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/admin/web/net/server/node_modules/express/lib/router/index.js:275:10)
    at /home/admin/web/net/server/index.js:125:5
    at Layer.handle [as handle_request] (/home/admin/web/net/server/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by ztomm** [comment]
A corrupted (origin) image will be skiped and the error is getting catched now. 

I appreciate your suggestions. The `onError` option won't work, it comes to late in process. But the idea for an alternative image is not bad. It could be a next feature.
